# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json to the container
COPY package*.json ./

# Install the application dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose the port your NestJS application will run on (adjust as needed)
EXPOSE 3000

# Start the NestJS application when the container starts
CMD ["npm", "start"]
